version: 2.1
orbs:
    katalon-studio: katalon/katalon-studio@23.0.8

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force https://heroku:c3631a7f-fa25-43d5-9489-69e66286c978@git.heroku.com/webinar-demo-kat-staging.git master
  test:
    steps:
        - katalon-studio/run:
                version: "latest"
                command_arguments: '-browserType="Chrome" -retry=2 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'
    
  deploy:
    docker:
      - image: buildpack-deps:trusty
      
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force https://heroku:c3631a7f-fa25-43d5-9489-69e66286c978@git.heroku.com/webinar-demo-kat-production.git master
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
